### ISSUE TITLE
Error when install pip install sentry-plugins

### ISSUE THREAD

**Issue by Nerdietony** [getsentry/sentry-plugins#132]
```
-bash: SyntaxError:: command not found
root@gembot:~# ^C
root@gembot:~# pip3 install sentry-plugins
Collecting sentry-plugins
  Using cached sentry_plugins-8.13.0-py2.py3-none-any.whl
Collecting PyJWT (from sentry-plugins)
  Using cached PyJWT-1.4.2-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.5/dist-packages (from sentry-plugins)
Requirement already satisfied: requests-oauthlib>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from sentry-plugins)
Collecting BeautifulSoup>=3.2.1 (from sentry-plugins)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r6aoot0h/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'


```

Help?

**Comment by mattrobenolt** [comment]
Sentry does not support Python 3.

**Comment by BenderV** [comment]
@mattrobenolt do you have any plans to ?

**Comment by mattrobenolt** [comment]
Not in any near term.
