### ISSUE TITLE
Error when running hipchat migration

### ISSUE THREAD

**Issue by iJebus** [getsentry/sentry-plugins#140]
I noted that there was another issue open with migration issues for hipchat, but it appears to be a different error, so, new issue.

For context, this is a sentry installation using Postgresql that has previously used the hipchat plugin before it was merged into sentry-plugins. 

```
Running migrations for hipchat_ac:
 - Migrating forwards to 0002_auto__del_mentionedevent.
 > hipchat_ac:0001_initial
FATAL ERROR - The following SQL query failed: CREATE TABLE "sentry_hipchat_ac_tenant" ("id" varchar(40) NOT NULL PRIMARY KEY, "room_id" varchar(40) NOT NULL, "room_name" varchar(200) NULL, "room_owner_id" varchar(40) NULL, "room_owner_name" varchar(200) NULL, "secret" varchar(120) NOT NULL, "homepage" varchar(250) NOT NULL, "token_url" varchar(250) NOT NULL, "capabilities_url" varchar(250) NOT NULL, "api_base_url" varchar(250) NOT NULL, "installed_from" varchar(250) NOT NULL, "auth_user_id" integer NULL)
The error was: ProgrammingError('relation "sentry_hipchat_ac_tenant" already exists\n',)
SQL: CREATE TABLE "sentry_hipchat_ac_tenant" ("id" varchar(40) NOT NULL PRIMARY KEY, "room_id" varchar(40) NOT NULL, "room_name" varchar(200) NULL, "room_owner_id" varchar(40) NULL, "room_owner_name" varchar(200) NULL, "secret" varchar(120) NOT NULL, "homepage" varchar(250) NOT NULL, "token_url" varchar(250) NOT NULL, "capabilities_url" varchar(250) NOT NULL, "api_base_url" varchar(250) NOT NULL, "installed_from" varchar(250) NOT NULL, "auth_user_id" integer NULL)
Error in migration: hipchat_ac:0001_initial
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 60, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 29, in _upgrade
    verbosity=verbosity,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/usr/local/lib/python2.7/site-packages/sentry_plugins/hipchat_ac/migrations/0001_initial.py", line 36, in forwards
    ('auth_user', self.gf('sentry.db.models.fields.foreignkey.FlexibleForeignKey')(related_name='hipchat_tenant_set', null=True, to=orm['sentry.User'])),
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 361, in create_table
    "columns": ', '.join([col for col in columns if col]),
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ProgrammingError('relation "sentry_hipchat_ac_tenant" already exists\n',)
SQL: CREATE TABLE "sentry_hipchat_ac_tenant" ("id" varchar(40) NOT NULL PRIMARY KEY, "room_id" varchar(40) NOT NULL, "room_name" varchar(200) NULL, "room_owner_id" varchar(40) NULL, "room_owner_name" varchar(200) NULL, "secret" varchar(120) NOT NULL, "homepage" varchar(250) NOT NULL, "token_url" varchar(250) NOT NULL, "capabilities_url" varchar(250) NOT NULL, "api_base_url" varchar(250) NOT NULL, "installed_from" varchar(250) NOT NULL, "auth_user_id" integer NULL)
```

**Comment by iJebus** [comment]
I didn't see there was a closed issue for this exact problem, though. Oops!
