### ISSUE TITLE
Sentry integration with Pivotal doesn't work

### ISSUE THREAD

**Issue by siddharth96** [getsentry/sentry-plugins#161]
Hi There,

I'm using Sentry as a Cloud service & have enabled integration with Pivotal.
However, the events pushed to Sentry aren't creating any story on the Pivotal tracker.

<img width="1000" alt="screen shot 2017-04-13 at 12 54 46 pm" src="https://cloud.githubusercontent.com/assets/1667655/24994438/756a4b06-2048-11e7-910a-a5b88e804e44.png">

PS: I'm using a free account right now.

**Comment by siddharth96** [comment]
When creating issue in Pivotal tracker from ```/issues/<issue-id>``` page, it says "Error communicating with Pivotal Tracker".
Chrome's inspect console, shows following details (session details omitted):
Endpoint: ```https://sentry.io/api/0/issues/<issue-id>/plugins/pivotal/create/```
Response headers:
```
HTTP/1.1 400 BAD REQUEST
Server: nginx
Date: Mon, 08 May 2017 17:05:16 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 95
Connection: keep-alive
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Language: en
Vary: Accept-Language, Cookie
Allow: GET, POST, HEAD, OPTIONS
Access-Control-Allow-Origin: https://sentry.io
Access-Control-Allow-Methods: get, post, put, patch, delete, head, options, trace
X-Frame-Options: deny
X-Served-By: app-9f9cb9
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

Request headers:
```
POST /api/0/issues/268876615/plugins/pivotal/create/ HTTP/1.1
Host: sentry.io
Connection: keep-alive
Content-Length: 1020
Pragma: no-cache
Cache-Control: no-cache
Origin: https://sentry.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Content-Type: application/json
Accept: application/json; charset=utf-8
X-Requested-With: XMLHttpRequest
DNT: 1
Referer: https://sentry.io/cleartax-lu/cleargst-backend/issues/268876615/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8,en-GB;q=0.6,hi;q=0.4
```

Request Payload (names truncated):
```
{"title":"FileNotFoundException: /tmp/28F7365295721Z5_finalrp_2017-05-08.xyz (No such file or directory)","description":"https://sentry.io/<url>/\n\n```\nFileNotFoundException: /tmp/tmp/28F7365295721Z5_finalrp_2017-05-08 15:23:06.833.xlsx (No such file or directory)\n    at pkg.mpl.Impl.download(Impl.java:40)\n    at pkg.mpl.Impl.downloadFile(Impl.java:415)\n    at pkg.mpl.Impl.startAsyncParsing(Impl.java:461)\n    at pkg.resources.Resource.startAsyncParsing(Resource.java:51)\n    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)\n...\n(68 additional frame(s) were not displayed)\n\nError handling a request: 6325726552a9c7db\n```"}
```

**Comment by siddharth96** [comment]
Any update on this?

**Comment by siddharth96** [comment]
Thank you for fixing. I'll close this issue.

**Comment by Akash91** [comment]
khaali baitha hai kya?
