### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by radoslavius** [getsentry/sentry-plugins#326]
Hi,
today I successfully installed sentry according to this guide - https://blog.driftingruby.com/configuring-a-sentry-server-on-ubuntu-16-04-lts/. But instalation of sentry-plugins fails:
```
(sentry_app) sentry@sentry:~$ pip install sentry-plugins
Collecting sentry-plugins
  Using cached sentry_plugins-8.22.0-py2.py3-none-any.whl
Collecting python-dateutil (from sentry-plugins)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting requests-oauthlib>=0.3.0 (from sentry-plugins)
  Using cached requests_oauthlib-0.8.0-py2.py3-none-any.whl
Collecting BeautifulSoup>=3.2.1 (from sentry-plugins)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3h2z2964/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3h2z2964/BeautifulSoup/
```
OS is fresh installed and updated ubuntu server 16.04.3 LTS.
What am I doing wrong?
Thanks

**Comment by radoslavius** [comment]
I found the solution according to a tip from my friend:
`This error message means that you are attempting to use Python 3 to follow an example or run a program that uses the Python 2 print statement.`

According to the above mentioned guideline, I proceeded as follows:
```
pip2.7 install sentry-plugins
sentry upgrade
sudo supervisorctl restart all
```
