### ISSUE TITLE
GitLab 404

### ISSUE THREAD

**Issue by lippoliv** [getsentry/sentry-plugins#34]
Hey there,
I always get GitLab 404-Error while configuring the Plugin.

![unbenannt](https://cloud.githubusercontent.com/assets/2561859/18984399/a2393556-86f2-11e6-84fe-774203af2eb7.PNG)

Here's the information about GitLab
![unbenannt](https://cloud.githubusercontent.com/assets/2561859/18984428/c70353d0-86f2-11e6-91d6-4d7dd30beded.PNG)

What did I do wrong?

I tryed my own "Private Token" and also the "Personal Access Tokens"

**Comment by fboutin-pmc** [comment]
It used to work really well, then we updated gitlab and now we get the same problem as yours. The plugin seems broken to me rather than you are doing something wrong.

**Comment by mattrobenolt** [comment]
Is your hosted GitLab on your internal network or on a private IP address? If so, out of the box, the request is going to be blocked. This is done to prevent abuse of being able to poke at internal networks.

Try setting `SENTRY_DISALLOWED_IPS` in your `sentry.conf.py` to an empty list. Since 8.2 though, this value should already be an empty list, so my guess is you're pre 8.2.

**Comment by lippoliv** [comment]
Hey @mattrobenolt,
as you can see my GitLab is reachable through an "official" URL. The Server is locatet in FR.

What do you mean with `sentry.conf.py`? Where is this file located? I just see an GUI to configure some Settings as you can see in the Screenshot.

**Comment by lippoliv** [comment]
@mattrobenolt OK now I got that I could Setup my own Sentry. really nice. I Setup an Docker Container wich is running good and I added you Extension. All the newest versions.

Now I can configure the Extension. But as soon as an Issue should be created, an Error raises:


```
172.17.0.1 - - [09/Oct/2016:11:42:20 +0000] "PUT /api/0/projects/sentry/project1/issues/?id=1 HTTP/1.0" 200 285 "https://sentry.lipperts-web.de/sentry/project1/issues/1/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
172.17.0.1 - - [09/Oct/2016:11:42:24 +0000] "GET /sentry/project1/issues/1/actions/gitlab/ HTTP/1.0" 200 11282 "https://sentry.lipperts-web.de/sentry/project1/issues/1/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 190, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/group_plugin_action.py", line 24, in handle
    response = plugin.get_view_response(request, group)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/base/v1.py", line 301, in get_view_response
    response = self.view(request, group)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/issue.py", line 231, in view
    request=request,
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_gitlab/plugin.py", line 88, in create_issue
    proj = gl.Project(id=repo_url)
AttributeError: 'Gitlab' object has no attribute 'Project'
11:42:30 [ERROR] django.request: Internal Server Error: /sentry/project1/issues/1/actions/gitlab/ (status_code=500 request=<WSGIRequest
path:/sentry/project1/issues/1/actions/gitlab/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'title': [u"TypeError: Object [object Object] has no method 'updateFrom'"], u'csrfmiddlewaretoken': [u'FtM2Jfzz3BbL6O3zVuLJbngYmOwLIBoG'], u'op': [u'create'], u'description': [u"https://sentry.lipperts-web.de/sentry/project1/issues/1/\r\n\r\n```\r\nTypeError: Object [object Object] has no method 'updateFrom'\r\n  at poll (../../sentry/scripts/views.js:389:46)\r\n  at merge (../../sentry/scripts/views.js:268:16)\r\n  at member (../../sentry/scripts/views.js:283:50)\r\n\r\nThis is an example javascript exception\r\n```"], u'next': [u'']}>,
COOKIES:{'_pk_id.30.48d3': '847dc9398583d944.1449306146.20.1474108416.1474108414.',
 '_pk_ref.30.48d3': '%5B%22%22%2C%22%22%2C1474108414%2C%22http%3A%2F%2Fwordpress.lc%2F%22%5D',
 'sc': 'FtM2Jfzz3BbL6O3zVuLJbngYmOwLIBoG',
 'sentrysid': '.eJxrYKotZNQI5UxMLsksS80vSi9kimBjYGAoTs0rKaosZA5lKS5NyY_gAQpZ-kTmmLllZmaFGaVEcAEFSlKLS5Lz87MzU8FayvOLslNTQnnjE0tLMuJLi1OL4jNTvBlDhZAEkhKTs1PzUkKVIObrlZZk5hTrgeT1XHMTM3McgSwniJpSPQDOQTOm:1btB10:9mUxjWq72AiFnpXXZ4BCkOdS46o',
 'sudo': '9LYl6FiijV2d:1btB10:bbrlsMsEeQqq3pBiP_1CGBvTOGw',
 'wp-settings-1': 'hidetb%3D1%26editor%3Dtinymce%26wplink%3D1%26libraryContent%3Dbrowse%26align%3Dcenter%26imgsize%3Dfull%26urlbutton%3Dnone%26editor_expand%3Don%26post_dfw%3Doff%26edit_element_vcUIPanelWidth%3D650%26edit_element_vcUIPanelLeft%3D1190px%26edit_element_vcUIPanelTop%3D84px',
 'wp-settings-time-1': '1475325321'},
META:{'CONTENT_LENGTH': '628',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
 u'CSRF_COOKIE': u'FtM2Jfzz3BbL6O3zVuLJbngYmOwLIBoG',
 'HTTP_ACCEPT': 'text/html, application/xhtml+xml, image/jxr, */*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.5',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'wp-settings-1=hidetb%3D1%26editor%3Dtinymce%26wplink%3D1%26libraryContent%3Dbrowse%26align%3Dcenter%26imgsize%3Dfull%26urlbutton%3Dnone%26editor_expand%3Don%26post_dfw%3Doff%26edit_element_vcUIPanelWidth%3D650%26edit_element_vcUIPanelLeft%3D1190px%26edit_element_vcUIPanelTop%3D84px; wp-settings-time-1=1475325321; _pk_id.30.48d3=847dc9398583d944.1449306146.20.1474108416.1474108414.; _pk_ref.30.48d3=%5B%22%22%2C%22%22%2C1474108414%2C%22http%3A%2F%2Fwordpress.lc%2F%22%5D; sentrysid=".eJxrYKotZNQI5UxMLsksS80vSi9kimBjYGAoTs0rKaosZA5lKS5NyY_gAQpZ-kTmmLllZmaFGaVEcAEFSlKLS5Lz87MzU8FayvOLslNTQnnjE0tLMuJLi1OL4jNTvBlDhZAEkhKTs1PzUkKVIObrlZZk5hTrgeT1XHMTM3McgSwniJpSPQDOQTOm:1btB10:9mUxjWq72AiFnpXXZ4BCkOdS46o"; sc=FtM2Jfzz3BbL6O3zVuLJbngYmOwLIBoG; sudo="9LYl6FiijV2d:1btB10:bbrlsMsEeQqq3pBiP_1CGBvTOGw"',
 'HTTP_HOST': 'sentry.lipperts-web.de',
 'HTTP_REFERER': 'https://sentry.lipperts-web.de/sentry/project1/issues/1/actions/gitlab/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393',
 'HTTP_X_FORWARDED_FOR': '77.21.106.173',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_REAL_IP': '77.21.106.173',
 'PATH_INFO': u'/sentry/project1/issues/1/actions/gitlab/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '77.21.106.173',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/sentry/project1/issues/1/actions/gitlab/',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'c620a0963df9',
 'SERVER_PORT': '9000',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'uwsgi.core': 0,
 'uwsgi.node': 'c620a0963df9',
 'uwsgi.version': '2.0.14',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7fd2d9f06f60>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7fd2cb906600>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>)
```

All is online available: GitLab at https://lw-scm.de and Sentry at https://sentry.lipperts-web.de (currently no official HTTPS, waiting for it)

What can I do

**Comment by mattrobenolt** [comment]
@lippoliv it looks like you found the correct error.

As for this ticket, going to close since that error is specifically related to `sentry-gitlab` and not this `sentry-plugins`. Which that said, at this point, `sentry-gitlab` should probably be considered deprecated and `sentry-plugins` supersedes it. If you uninstall `sentry-gitlab` in this case, everything should be fine.

**Comment by lippoliv** [comment]
OK thought both are same plugins.

I am not able to move over to sentry-plugins, the pip install exists with Code 1

```
Collecting https://github.com/getsentry/sentry-plugins/archive/master.zip
  Downloading https://github.com/getsentry/sentry-plugins/archive/master.zip (144kB)
Collecting BeautifulSoup>=3.2.1 (from sentry-plugins==0.1.2)
  Downloading BeautifulSoup-3.2.1.tar.gz
Collecting PyJWT (from sentry-plugins==0.1.2)
  Downloading PyJWT-1.4.2-py2.py3-none-any.whl
Installing collected packages: BeautifulSoup, PyJWT, sentry-plugins
  Running setup.py install for BeautifulSoup: started
    Running setup.py install for BeautifulSoup: finished with status 'done'
  Running setup.py install for sentry-plugins: started
    Running setup.py install for sentry-plugins: finished with status 'error'
    Complete output from command /usr/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-sLCb9p-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pe1_Q4-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/sentry_plugins
    copying src/sentry_plugins/base.py -> build/lib/sentry_plugins
    copying src/sentry_plugins/exceptions.py -> build/lib/sentry_plugins
    copying src/sentry_plugins/__init__.py -> build/lib/sentry_plugins
    creating build/lib/sentry_plugins/jira_ac
    copying src/sentry_plugins/jira_ac/utils.py -> build/lib/sentry_plugins/jira_ac
    copying src/sentry_plugins/jira_ac/urls.py -> build/lib/sentry_plugins/jira_ac
    copying src/sentry_plugins/jira_ac/models.py -> build/lib/sentry_plugins/jira_ac
    copying src/sentry_plugins/jira_ac/views.py -> build/lib/sentry_plugins/jira_ac
    copying src/sentry_plugins/jira_ac/forms.py -> build/lib/sentry_plugins/jira_ac
    copying src/sentry_plugins/jira_ac/__init__.py -> build/lib/sentry_plugins/jira_ac
    copying src/sentry_plugins/jira_ac/plugin.py -> build/lib/sentry_plugins/jira_ac
    creating build/lib/sentry_plugins/jira
    copying src/sentry_plugins/jira/client.py -> build/lib/sentry_plugins/jira
    copying src/sentry_plugins/jira/__init__.py -> build/lib/sentry_plugins/jira
    copying src/sentry_plugins/jira/plugin.py -> build/lib/sentry_plugins/jira
    creating build/lib/sentry_plugins/pivotal
    copying src/sentry_plugins/pivotal/__init__.py -> build/lib/sentry_plugins/pivotal
    copying src/sentry_plugins/pivotal/plugin.py -> build/lib/sentry_plugins/pivotal
    creating build/lib/sentry_plugins/github
    copying src/sentry_plugins/github/client.py -> build/lib/sentry_plugins/github
    copying src/sentry_plugins/github/__init__.py -> build/lib/sentry_plugins/github
    copying src/sentry_plugins/github/plugin.py -> build/lib/sentry_plugins/github
    creating build/lib/sentry_plugins/pushover
    copying src/sentry_plugins/pushover/client.py -> build/lib/sentry_plugins/pushover
    copying src/sentry_plugins/pushover/__init__.py -> build/lib/sentry_plugins/pushover
    copying src/sentry_plugins/pushover/plugin.py -> build/lib/sentry_plugins/pushover
    creating build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/testutils.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/utils.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/cards.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/mentions.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/urls.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/models.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/views.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/__init__.py -> build/lib/sentry_plugins/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/plugin.py -> build/lib/sentry_plugins/hipchat_ac
    creating build/lib/sentry_plugins/pagerduty
    copying src/sentry_plugins/pagerduty/client.py -> build/lib/sentry_plugins/pagerduty
    copying src/sentry_plugins/pagerduty/__init__.py -> build/lib/sentry_plugins/pagerduty
    copying src/sentry_plugins/pagerduty/plugin.py -> build/lib/sentry_plugins/pagerduty
    creating build/lib/sentry_plugins/gitlab
    copying src/sentry_plugins/gitlab/client.py -> build/lib/sentry_plugins/gitlab
    copying src/sentry_plugins/gitlab/endpoints.py -> build/lib/sentry_plugins/gitlab
    copying src/sentry_plugins/gitlab/__init__.py -> build/lib/sentry_plugins/gitlab
    copying src/sentry_plugins/gitlab/plugin.py -> build/lib/sentry_plugins/gitlab
    creating build/lib/sentry_plugins/jira_ac/south_migrations
    copying src/sentry_plugins/jira_ac/south_migrations/0001_initial.py -> build/lib/sentry_plugins/jira_ac/south_migrations
    copying src/sentry_plugins/jira_ac/south_migrations/__init__.py -> build/lib/sentry_plugins/jira_ac/south_migrations
    creating build/lib/sentry_plugins/hipchat_ac/migrations
    copying src/sentry_plugins/hipchat_ac/migrations/0001_initial.py -> build/lib/sentry_plugins/hipchat_ac/migrations
    copying src/sentry_plugins/hipchat_ac/migrations/0002_auto__del_mentionedevent.py -> build/lib/sentry_plugins/hipchat_ac/migrations
    copying src/sentry_plugins/hipchat_ac/migrations/__init__.py -> build/lib/sentry_plugins/hipchat_ac/migrations
    creating build/lib/sentry_plugins/hipchat_ac/endpoints
    copying src/sentry_plugins/hipchat_ac/endpoints/test_config.py -> build/lib/sentry_plugins/hipchat_ac/endpoints
    copying src/sentry_plugins/hipchat_ac/endpoints/__init__.py -> build/lib/sentry_plugins/hipchat_ac/endpoints
    copying src/sentry_plugins/hipchat_ac/endpoints/tenants.py -> build/lib/sentry_plugins/hipchat_ac/endpoints
    running egg_info
    creating src/sentry_plugins.egg-info
    writing requirements to src/sentry_plugins.egg-info/requires.txt
    writing src/sentry_plugins.egg-info/PKG-INFO
    writing top-level names to src/sentry_plugins.egg-info/top_level.txt
    writing dependency_links to src/sentry_plugins.egg-info/dependency_links.txt
    writing entry points to src/sentry_plugins.egg-info/entry_points.txt
    writing manifest file 'src/sentry_plugins.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'src/sentry_plugins.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'src/sentry_plugins/assets.json'
    warning: no files found matching '*.js.gz' under directory 'src/sentry_plugins'
    warning: no files found matching '*.js.map' under directory 'src/sentry_plugins'
    warning: no previously-included files matching '*~' found anywhere in distribution
    writing manifest file 'src/sentry_plugins.egg-info/SOURCES.txt'
    creating build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/base.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/config.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/error.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/signin.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/widget.html -> build/lib/sentry_plugins/jira_ac/templates
    creating build/lib/sentry_plugins/jira/static
    creating build/lib/sentry_plugins/jira/static/jira
    copying src/sentry_plugins/jira/static/jira/jira.jsx -> build/lib/sentry_plugins/jira/static/jira
    creating build/lib/sentry_plugins/jira/static/jira/components
    copying src/sentry_plugins/jira/static/jira/components/issueActions.jsx -> build/lib/sentry_plugins/jira/static/jira/components
    copying src/sentry_plugins/jira/static/jira/components/settings.jsx -> build/lib/sentry_plugins/jira/static/jira/components
    creating build/lib/sentry_plugins/hipchat_ac/static
    creating build/lib/sentry_plugins/hipchat_ac/static/hipchat_ac
    copying src/sentry_plugins/hipchat_ac/static/hipchat_ac/hipchat_ac.jsx -> build/lib/sentry_plugins/hipchat_ac/static/hipchat_ac
    creating build/lib/sentry_plugins/hipchat_ac/static/hipchat_ac/components
    copying src/sentry_plugins/hipchat_ac/static/hipchat_ac/components/settings.jsx -> build/lib/sentry_plugins/hipchat_ac/static/hipchat_ac/components
    creating build/lib/sentry_plugins/hipchat_ac/static/sentry_hipchat_ac
    creating build/lib/sentry_plugins/hipchat_ac/static/sentry_hipchat_ac/css
    copying src/sentry_plugins/hipchat_ac/static/sentry_hipchat_ac/css/sentry-hipchat-ac.css -> build/lib/sentry_plugins/hipchat_ac/static/sentry_hipchat_ac/css
    creating build/lib/sentry_plugins/hipchat_ac/static/sentry_hipchat_ac/js
    copying src/sentry_plugins/hipchat_ac/static/sentry_hipchat_ac/js/iframe.js -> build/lib/sentry_plugins/hipchat_ac/static/sentry_hipchat_ac/js
    creating build/lib/sentry_plugins/hipchat_ac/templates
    creating build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/assign_event.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/configure.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/configure_layout.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/configure_plugin.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/event_details.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/layout.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/recent_events.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    copying src/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac/sign_out.html -> build/lib/sentry_plugins/hipchat_ac/templates/sentry_hipchat_ac
    running build_assets
    using node (v6.7.0) and npm (3.10.3)
    npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz
    node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.7.0 (node-v48 ABI) (falling back to source compile with node-gyp)
    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
    pulled version information from 'sentry' module
    building assets for sentry-plugins v0.1.2 (build UNKNOWN)
    Could not determine sentry version or build
    
    ----------------------------------------
Command "/usr/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-sLCb9p-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pe1_Q4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-sLCb9p-build/
The command '/bin/sh -c pip install https://github.com/getsentry/sentry-plugins/archive/master.zip' returned a non-zero code: 1
ERROR: Build failed: exit code 1
```

May others will get that too as they read this issue... Any ideas?

**Comment by flower189** [comment]
Hi
We're currently running Sentry 8.10 in Docker and GitLab 8.13 and are also experiencing this issue with the GitLab integration. It works fine in the settings but when trying to create a new issue in GitLab or link to an existing issue it displays the same 404 error.

Our Allowed IPs list just contains * and the disallowed IPs list is empty.

**Comment by mattrobenolt** [comment]
We think this is part of the problem: https://gitlab.com/gitlab-org/gitlab-ce/issues/15651

**Comment by lippoliv** [comment]
@mattrobenolt I do not have a `.` in my ID

**Comment by mattrobenolt** [comment]
Is this on sentry.io or on-premise?

**Comment by lippoliv** [comment]
If "on-premise" means self-hosted: Self-Hosted. But I had the same Problem with the same Project on sentry.io too

**Comment by mattrobenolt** [comment]
Can you contact support and I'll investigate? There's not much I can do for your own install. :)

**Comment by lippoliv** [comment]
I cant understand your comment. Of Course, you'll not Login to my sentry and start analysing. But hey: Try get it running on sentry.io, that won't work. I can't submit a Ticket:

> Email support is reserved for paying Sentry customers. If you need help, please refer to the community support options, or consider upgrading to a paid plan.

I will not use sentry.io as of I am running my own Server now, wich fits perfeclty my needs :)

Hopefully your Analyse will not stop here, there are a lot users affected by this Problem.

**Comment by douglarek** [comment]
Any progress ?  I am using GitLab 8.14.2, and it does not work too.

**Comment by mattrobenolt** [comment]
@douglarek unless something has changed, this is still a problem with GitLab that we can't do anything about.

**Comment by uda** [comment]
Please re-open this.
In my case, the issue is the `/` in the namespace, according to the docs, you should use `%2F` as `NAMESPACE` and `PROJECT_NAME` separator.

It appears we don't escape the slash, but we do the percent, so when I tried setting `%2F` I got `%25%2F` on gitlab's end, and again received a 404.

See: https://gitlab.com/help/api/projects.md#get-single-project

**Comment by chrisdrackett** [comment]
@uda worth creating a new issue? I'm running into this as well :)
