### ISSUE TITLE
sentry.tasks.commits: fetch_commits.error

### ISSUE THREAD

**Issue by artful88533** [getsentry/sentry-plugins#415]
Hello!
I have problem. 
When run `sentry-cli releases set-commits v0.1.7 --auto`
I see in log sentry worker:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/commits.py", line 123, in fetch_commits
    repo_commits = provider.compare_commits(repo, start_sha, end_sha, actor=user)
  File "/usr/local/lib/python2.7/site-packages/sentry_plugins/github/plugin.py", line 415, in compare_commits
    client = self.get_client(actor)
  File "/usr/local/lib/python2.7/site-packages/sentry_plugins/github/plugin.py", line 57, in get_client
    raise PluginError(API_ERRORS[401])
PluginError: Unauthorized: either your access token was invalid or you do not have access
16:35:34 [ERROR] sentry.tasks.commits: fetch_commits.error (organization_id=1 user_id=7 repository=u'myorg/test-repo' start_sha=u'a8a328a0e1f85521742d241b50d7c68db5d1d231' end_sha=u'a63163797c1f33777d61f6216f19937711ab4cba')
```
Sentry configured with:
```
GITHUB_APP_ID = 'My GitHub Application Client ID'
GITHUB_API_SECRET = 'My GitHub Application Client Secret'
GITHUB_EXTENDED_PERMISSIONS = ['repo']
```
Repository has added to Repositories in sentry.

Github user has Admin permission to this repository.

What I do wrong?
Thank You!

**Comment by markstory** [comment]
Looks like GitHub disagrees with you. Have you tried testing your API key/secret with Curl or another github client library?

**Comment by artful88533** [comment]
Can I use **Personal access** tokens instead **OAuth Apps** ?
